apiVersion: v1
entries:
  ako:
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2020-07-22T12:10:35.896503+05:30"
    description: A helm chart for Avi Kubernetes Operator
    digest: ffeaac645a5b9f3fb04627f0f8a7bdc6af76869126e8d0333ab74eab7f90796e
    name: ako
    type: application
    urls:
    - https://avinetworks.github.io/avi-helm-charts/charts/stable/ako/ako-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v2
    appVersion: 0.9.1
    created: "2020-07-22T12:10:35.8941+05:30"
    description: A helm chart for Avi Kubernetes Operator
    digest: b24b1d7b4a8fafe09a34d51dbcb13db1be4c38785a85bfb3f363150c826ff3e5
    name: ako
    type: application
    urls:
    - https://avinetworks.github.io/avi-helm-charts/charts/stable/ako/ako-0.9.1.tgz
    version: 0.9.1
generated: "2020-07-22T12:10:35.884357+05:30"
